#!/bin/bash -vex

# Wait for cloud-init to finish initializing.
while [ ! -e /var/lib/cloud/instance/boot-finished ]; do
    echo "waiting on cloud-init to finish..."
    sleep 1
done

export TMPDIR="/mnt/docker-tmp"
export DOCKER_OPTS="--ipv6 --fixed-cidr-v6=fd15:4ba5:5a2b:100a::/64 -s overlay2 --icc=false --iptables=true"
